/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatRouteImport } from './routes/stat'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RepeatedShareRouteImport } from './routes/repeated-share'
import { Route as RepeatedRouteImport } from './routes/repeated'
import { Route as MissingRouteImport } from './routes/missing'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIndexRouteImport } from './routes/share/index'
import { Route as RepeatedShareIndexRouteImport } from './routes/repeated-share/index'
import { Route as AlbumIndexRouteImport } from './routes/album/index'
import { Route as SharePreviewRouteImport } from './routes/share/preview'
import { Route as RepeatedSharePreviewRouteImport } from './routes/repeated-share/preview'
import { Route as AlbumPageIdRouteImport } from './routes/album/$pageId'
import { Route as AlbumGroupPageIdRouteImport } from './routes/album/$group/$pageId'

const StatRoute = StatRouteImport.update({
  id: '/stat',
  path: '/stat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RepeatedShareRoute = RepeatedShareRouteImport.update({
  id: '/repeated-share',
  path: '/repeated-share',
  getParentRoute: () => rootRouteImport,
} as any)
const RepeatedRoute = RepeatedRouteImport.update({
  id: '/repeated',
  path: '/repeated',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingRoute = MissingRouteImport.update({
  id: '/missing',
  path: '/missing',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareRoute,
} as any)
const RepeatedShareIndexRoute = RepeatedShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepeatedShareRoute,
} as any)
const AlbumIndexRoute = AlbumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumRoute,
} as any)
const SharePreviewRoute = SharePreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ShareRoute,
} as any)
const RepeatedSharePreviewRoute = RepeatedSharePreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => RepeatedShareRoute,
} as any)
const AlbumPageIdRoute = AlbumPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AlbumRoute,
} as any)
const AlbumGroupPageIdRoute = AlbumGroupPageIdRouteImport.update({
  id: '/$group/$pageId',
  path: '/$group/$pageId',
  getParentRoute: () => AlbumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRouteWithChildren
  '/missing': typeof MissingRoute
  '/repeated': typeof RepeatedRoute
  '/repeated-share': typeof RepeatedShareRouteWithChildren
  '/scanner': typeof ScannerRoute
  '/share': typeof ShareRouteWithChildren
  '/stat': typeof StatRoute
  '/album/$pageId': typeof AlbumPageIdRoute
  '/repeated-share/preview': typeof RepeatedSharePreviewRoute
  '/share/preview': typeof SharePreviewRoute
  '/album/': typeof AlbumIndexRoute
  '/repeated-share/': typeof RepeatedShareIndexRoute
  '/share/': typeof ShareIndexRoute
  '/album/$group/$pageId': typeof AlbumGroupPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missing': typeof MissingRoute
  '/repeated': typeof RepeatedRoute
  '/scanner': typeof ScannerRoute
  '/stat': typeof StatRoute
  '/album/$pageId': typeof AlbumPageIdRoute
  '/repeated-share/preview': typeof RepeatedSharePreviewRoute
  '/share/preview': typeof SharePreviewRoute
  '/album': typeof AlbumIndexRoute
  '/repeated-share': typeof RepeatedShareIndexRoute
  '/share': typeof ShareIndexRoute
  '/album/$group/$pageId': typeof AlbumGroupPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRouteWithChildren
  '/missing': typeof MissingRoute
  '/repeated': typeof RepeatedRoute
  '/repeated-share': typeof RepeatedShareRouteWithChildren
  '/scanner': typeof ScannerRoute
  '/share': typeof ShareRouteWithChildren
  '/stat': typeof StatRoute
  '/album/$pageId': typeof AlbumPageIdRoute
  '/repeated-share/preview': typeof RepeatedSharePreviewRoute
  '/share/preview': typeof SharePreviewRoute
  '/album/': typeof AlbumIndexRoute
  '/repeated-share/': typeof RepeatedShareIndexRoute
  '/share/': typeof ShareIndexRoute
  '/album/$group/$pageId': typeof AlbumGroupPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/missing'
    | '/repeated'
    | '/repeated-share'
    | '/scanner'
    | '/share'
    | '/stat'
    | '/album/$pageId'
    | '/repeated-share/preview'
    | '/share/preview'
    | '/album/'
    | '/repeated-share/'
    | '/share/'
    | '/album/$group/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/missing'
    | '/repeated'
    | '/scanner'
    | '/stat'
    | '/album/$pageId'
    | '/repeated-share/preview'
    | '/share/preview'
    | '/album'
    | '/repeated-share'
    | '/share'
    | '/album/$group/$pageId'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/missing'
    | '/repeated'
    | '/repeated-share'
    | '/scanner'
    | '/share'
    | '/stat'
    | '/album/$pageId'
    | '/repeated-share/preview'
    | '/share/preview'
    | '/album/'
    | '/repeated-share/'
    | '/share/'
    | '/album/$group/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRouteWithChildren
  MissingRoute: typeof MissingRoute
  RepeatedRoute: typeof RepeatedRoute
  RepeatedShareRoute: typeof RepeatedShareRouteWithChildren
  ScannerRoute: typeof ScannerRoute
  ShareRoute: typeof ShareRouteWithChildren
  StatRoute: typeof StatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stat': {
      id: '/stat'
      path: '/stat'
      fullPath: '/stat'
      preLoaderRoute: typeof StatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repeated-share': {
      id: '/repeated-share'
      path: '/repeated-share'
      fullPath: '/repeated-share'
      preLoaderRoute: typeof RepeatedShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repeated': {
      id: '/repeated'
      path: '/repeated'
      fullPath: '/repeated'
      preLoaderRoute: typeof RepeatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing': {
      id: '/missing'
      path: '/missing'
      fullPath: '/missing'
      preLoaderRoute: typeof MissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/'
      fullPath: '/share/'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof ShareRoute
    }
    '/repeated-share/': {
      id: '/repeated-share/'
      path: '/'
      fullPath: '/repeated-share/'
      preLoaderRoute: typeof RepeatedShareIndexRouteImport
      parentRoute: typeof RepeatedShareRoute
    }
    '/album/': {
      id: '/album/'
      path: '/'
      fullPath: '/album/'
      preLoaderRoute: typeof AlbumIndexRouteImport
      parentRoute: typeof AlbumRoute
    }
    '/share/preview': {
      id: '/share/preview'
      path: '/preview'
      fullPath: '/share/preview'
      preLoaderRoute: typeof SharePreviewRouteImport
      parentRoute: typeof ShareRoute
    }
    '/repeated-share/preview': {
      id: '/repeated-share/preview'
      path: '/preview'
      fullPath: '/repeated-share/preview'
      preLoaderRoute: typeof RepeatedSharePreviewRouteImport
      parentRoute: typeof RepeatedShareRoute
    }
    '/album/$pageId': {
      id: '/album/$pageId'
      path: '/$pageId'
      fullPath: '/album/$pageId'
      preLoaderRoute: typeof AlbumPageIdRouteImport
      parentRoute: typeof AlbumRoute
    }
    '/album/$group/$pageId': {
      id: '/album/$group/$pageId'
      path: '/$group/$pageId'
      fullPath: '/album/$group/$pageId'
      preLoaderRoute: typeof AlbumGroupPageIdRouteImport
      parentRoute: typeof AlbumRoute
    }
  }
}

interface AlbumRouteChildren {
  AlbumPageIdRoute: typeof AlbumPageIdRoute
  AlbumIndexRoute: typeof AlbumIndexRoute
  AlbumGroupPageIdRoute: typeof AlbumGroupPageIdRoute
}

const AlbumRouteChildren: AlbumRouteChildren = {
  AlbumPageIdRoute: AlbumPageIdRoute,
  AlbumIndexRoute: AlbumIndexRoute,
  AlbumGroupPageIdRoute: AlbumGroupPageIdRoute,
}

const AlbumRouteWithChildren = AlbumRoute._addFileChildren(AlbumRouteChildren)

interface RepeatedShareRouteChildren {
  RepeatedSharePreviewRoute: typeof RepeatedSharePreviewRoute
  RepeatedShareIndexRoute: typeof RepeatedShareIndexRoute
}

const RepeatedShareRouteChildren: RepeatedShareRouteChildren = {
  RepeatedSharePreviewRoute: RepeatedSharePreviewRoute,
  RepeatedShareIndexRoute: RepeatedShareIndexRoute,
}

const RepeatedShareRouteWithChildren = RepeatedShareRoute._addFileChildren(
  RepeatedShareRouteChildren,
)

interface ShareRouteChildren {
  SharePreviewRoute: typeof SharePreviewRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  SharePreviewRoute: SharePreviewRoute,
  ShareIndexRoute: ShareIndexRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRouteWithChildren,
  MissingRoute: MissingRoute,
  RepeatedRoute: RepeatedRoute,
  RepeatedShareRoute: RepeatedShareRouteWithChildren,
  ScannerRoute: ScannerRoute,
  ShareRoute: ShareRouteWithChildren,
  StatRoute: StatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
